import { z } from "zod";

/**
 * Knosia ID schema - validates IDs generated by TurboStarter's generateId()
 *
 * Format: 32-character alphanumeric string (base62)
 * Example: "HK9SO1TUY54PPAUDxJHFUgupuXTUqjA7"
 *
 * Note: We use generateId() from @turbostarter/shared/utils, NOT UUID.
 * This is intentional for:
 * - URL-friendliness (no dashes, shorter)
 * - Consistency with TurboStarter framework patterns
 * - Better readability in logs and debugging
 */
export const knosiaIdSchema = z
  .string()
  .min(1, "ID is required")
  .regex(/^[a-zA-Z0-9]+$/, "Invalid ID format");

/** Connection ID - references knosia_connection.id */
export const connectionIdSchema = knosiaIdSchema;

/** Organization ID - references knosia_organization.id (format: "user-{userId}") */
export const orgIdSchema = z.string().min(1, "Organization ID is required");

/** Analysis ID - references knosia_analysis.id */
export const analysisIdSchema = knosiaIdSchema;

/** Workspace ID - references knosia_workspace.id */
export const workspaceIdSchema = knosiaIdSchema;
