#!/usr/bin/env python3
"""
Generate or update barrel export file (index.ts) for components.

Usage:
  python generate-barrel.py <components_dir> [--dry-run]

Example:
  python generate-barrel.py src/renderer/components/
  python generate-barrel.py src/renderer/components/ --dry-run

Generates index.ts with exports for all .tsx files in the directory.
"""
import sys
from pathlib import Path
from datetime import datetime


# Files to exclude from barrel export
EXCLUDE_FILES = {
    'index.ts', 'index.tsx',
    'utils.ts', 'utils.tsx',
    'types.ts', 'types.tsx',
}

# Standard header for generated file
HEADER = '''/**
 * Component Barrel Exports
 * Auto-generated by generate-barrel.py
 * Last updated: {timestamp}
 *
 * DO NOT EDIT MANUALLY - regenerate with:
 *   python .context/workflows/scripts/generate-barrel.py {dir}
 */

'''


def get_component_files(components_dir: Path) -> list[str]:
    """Get sorted list of component files to export."""
    files = []

    for f in components_dir.glob("*.tsx"):
        if f.name not in EXCLUDE_FILES and not f.name.startswith('_'):
            files.append(f.stem)

    for f in components_dir.glob("*.ts"):
        if f.name not in EXCLUDE_FILES and not f.name.startswith('_'):
            if f.stem not in files:  # Don't duplicate if both .ts and .tsx exist
                files.append(f.stem)

    return sorted(files)


def generate_barrel_content(components_dir: Path, files: list[str]) -> str:
    """Generate the content for index.ts."""
    lines = [HEADER.format(timestamp=datetime.now().isoformat(), dir=components_dir)]

    # Check for utils.ts
    if (components_dir / 'utils.ts').exists() or (components_dir / 'utils.tsx').exists():
        lines.append("// Utilities")
        lines.append("export * from './utils';")
        lines.append("")

    # Check for types.ts
    if (components_dir / 'types.ts').exists() or (components_dir / 'types.tsx').exists():
        lines.append("// Types")
        lines.append("export * from './types';")
        lines.append("")

    # Component exports
    lines.append("// Components")
    for f in files:
        lines.append(f"export * from './{f}';")

    lines.append("")  # Trailing newline

    return "\n".join(lines)


def generate_barrel(components_dir: Path, dry_run: bool = False):
    """Generate barrel export file."""

    if not components_dir.exists():
        print(f"Error: Directory not found: {components_dir}", file=sys.stderr)
        return False

    files = get_component_files(components_dir)

    if not files:
        print(f"No component files found in {components_dir}")
        return False

    content = generate_barrel_content(components_dir, files)
    index_file = components_dir / 'index.ts'

    print(f"Components found: {len(files)}")
    for f in files:
        print(f"  - {f}")
    print()

    if dry_run:
        print("--- Generated content (dry run) ---")
        print(content)
        print("--- End ---")
    else:
        # Check if file exists and has manual edits
        if index_file.exists():
            existing = index_file.read_text()
            if "DO NOT EDIT MANUALLY" not in existing:
                print(f"⚠ Warning: {index_file} may have manual edits")
                print("  Backing up to index.ts.bak")
                (components_dir / 'index.ts.bak').write_text(existing)

        index_file.write_text(content)
        print(f"✓ Generated {index_file}")

    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate-barrel.py <components_dir> [--dry-run]")
        print("Example: python generate-barrel.py src/renderer/components/")
        sys.exit(1)

    components_dir = Path(sys.argv[1])
    dry_run = "--dry-run" in sys.argv

    success = generate_barrel(components_dir, dry_run)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
